---
name: Scope-OnExit
version: 0.01
author:
  - 'Leon Timmermans <leont@cpan.org>'
abstract: Running code on scope exit
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Scope-OnExit
  license: http://dev.perl.org/licenses/
configure_requires:
  Module::Build: 0
requires:
  perl: 5.006
build_requires:
  ExtUtils::CBuilder: 0
  Module::Build: 0
  Test::More: 0
provides:
  Scope::OnExit:
    file: lib/Scope/OnExit.pm
    version: 0.01
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
keywords:
  - scope
  - end
